SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `leaderboard`.`DATA_RESOURCE` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_id` INTEGER UNSIGNED,
  PRIMARY KEY(`id`),
  CONSTRAINT `DATA_RESOURCE_admin_id_fkc` FOREIGN KEY `DATA_RESOURCE_admin_id_fkc` (`admin_id`)
    REFERENCES `ADMIN` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL
)
TYPE = InnoDB;